### ISSUE TITLE
Remove dependency on minikube

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#121]
The `e2e` target in the Makefile [calls](https://github.com/kinvolk/habitat-operator/blob/371bbbad65de6aa8826c04fcd144deef833fa4a3/Makefile#L23) `minikube ip`.

It would be good not to expect a minikube installation to be present, and get the cluster IP some other way, e.g. by parsing `~/.kube/config`.

**Comment by zeenix** [comment]
Doesn't `--kubeconfig ~/.kube/config` part just before --ip option in the Makefile takes care of that?

**Comment by asymmetric** [comment]
It doesn't take care of that, but it contains the information we need, so one option is to parse that file instead of calling `minikube ip`.

**Comment by krnowak** [comment]
Probably this could be used:
- `kubectl config view --output=jsonpath='{.clusters[0].cluster.server}' | sed -e 's/.*\/\/\([0-9.]\+\).*/\1/'`
- `kubectl config view --output=jsonpath='{.clusters[0].cluster.server}' | grep --only-matching '[0-9.]\+' | head --lines 1`

Second one is easier to understand I think.

**Comment by asymmetric** [comment]
See #266: we can still use `minikube` locally but E2E tests will be run on Azure in the future during our CI process.

So this issue is still valid.
