### ISSUE TITLE
Skip tests on documentation and example changes

### ISSUE THREAD

**Issue by LiliC** [habitat-sh/habitat-operator#143]
Currently we run all our tests every time we open a PR, we should skip running that if only documentation change was made or one of the examples was changed, etc.

**Comment by LiliC** [comment]
@indradhanush I think you had a look at this at some point, maybe you can document your progress here? Thanks!

**Comment by kosyfrances** [comment]
I do not really see/understand how the tests run for documentation and example change.
cc: @iaguis  @krnowak @asymmetric @indradhanush

**Comment by iaguis** [comment]
We can get some inspiration [from rkt](https://github.com/rkt/rkt/blob/2de014aa1a8f1d9e92bc869e7d666679f2e45a1d/tests/build-and-run-tests.sh#L48)
