### ISSUE TITLE
Check what needs to be upgraded for client-go v6

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#171]
There are some [changes](http://blog.kubernetes.io/2018/01/introducing-client-go-version-6.html) to be made. Off the top of my head:

* `v1` instead of `v1beta1` for Deployments
* getting rid of [newListWatchFromClientWithLabels](
https://github.com/kinvolk/habitat-operator/tree/3fc2a17f09fbaa9088efc07fd1914f00909458cb/pkg/controller/utils.go#L66) and use `NewFilteredSharedInformerFactory`.

**Comment by LiliC** [comment]
I do not understand this issue, we are already at client-go v6.0.0?

**Comment by asymmetric** [comment]
Yes, but we haven't performed the changes in our codebase that can/should go along with it.

**Comment by LiliC** [comment]
Yes, those are nice to have, but not necessary to have things working. As deployments is supported for at least 1.9.x, maybe even more. This way we do not break compatibility with older k8s versions.

> getting rid of newListWatchFromClientWithLabels

Why is this needed?

**Comment by asymmetric** [comment]
That's a good point about compatibility. But at some point we have to update (`v1beta1.Deployment` will be deprecated and then removed at some point, I presume), and this issue can be useful to list what we need to do.

I edited my post above to answer your second point.

**Comment by LiliC** [comment]
> (v1beta1.Deployment will be deprecated and then removed at some point, I presume)

There is ongoing discussion to not deprecate versions as fast as it is currently, we will see what comes out of that.
