### ISSUE TITLE
Make code generation more reproducible

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#206]
Since the [code generator](https://github.com/kubernetes/code-generator) we use in the `Makefile` is not part of this repo (and cannot be, since `dep` does not support non-Go dependencies), there's a chance that different versions of it produce different outputs.

In order to solve this, we could:

* Make Travis clone the codegen repo (maybe at a stable tag/commit) and run [verify-codegen.sh](https://github.com/kubernetes/code-generator/blob/master/hack/verify-codegen.sh), making Travis the "source of truth"
* Add the codegen repo as a git submodule, making this repo the "source of truth"

I prefer the first solution, as git submodules are kind of a UX nightmare for everyone involved.

**Comment by zeenix** [comment]
> I prefer the first solution, as git submodules are kind of a UX nightmare for everyone involved.

The UX being not-so-great (nightmare is pushing it IMO) is typically worth using git submodules for cases where they make sense. I've seen people avoiding them and ending up with problems with their alternative solutions.

Having said that, the former sounds like a good solution as well.

**Comment by LiliC** [comment]
> Make Travis clone the codegen repo (maybe at a stable tag/commit) and run verify-codegen.sh, making Travis the "source of truth"

That sounds good. But I will quote you though, how much time would that add to the build time? ;) Having to run that each time would be a bit silly, considering that part of the code is not modified that often.

There is also the option of commit the script to our repo like they do in other projects.

**Comment by asymmetric** [comment]
> how much time would that add to the build time? ;)

A few dozen seconds ;)

> There is also the option of commiting the script to our repo like they do in other projects.

You mean the codegen code itself? As you saw, it gets updated, so how would we keep it in sync?

**Comment by LiliC** [comment]
> You mean the codegen code itself? As you saw, it gets updated, so how would we keep it in sync?

IMO when updating the client-go & co, should be in sync with that anyways, somehow.

**Comment by LiliC** [comment]
Think we agreed offline to go for the Travis option here.
