### ISSUE TITLE
ConfigMap not deleted when Habitat resource is deleted

### ISSUE THREAD

**Issue by LiliC** [habitat-sh/habitat-operator#213]
When requesting to delete a Habitat resource, only the `Deployment` is deleted, but the `ConfigMap` is just updated. If there are no running Habitat resources in that Namespace a `ConfigMap` and any other other resource the habitat-operator creates should be cleaned up as well.

cc @asymmetric

**Comment by asymmetric** [comment]
This is actually not the case anymore.
