### ISSUE TITLE
Support double signal handling

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#220]
See [this](https://github.com/kubernetes/sample-controller/blob/master/pkg/signals/signal.go).

This allows us to exit immediately if we receive two signals, in addition to exiting gracefully if we only receive one.

**Comment by krnowak** [comment]
To reproduce, start the operator in terminal, outside the kubernetes cluster. And then press ctrl-c. Currently it prints something like "received SIGTERM, exiting gracefully", and what we want there [I guess :)] is to have ctrl-c to trigger the cancel function of the context, which in turn would make all the goroutines to quit, which would result in a graceful shut down of the operator (so it would print something like "context channel closed, exiting"). If something hangs, second ctrl-c would just shut down the operator right away.

For more context (sorry for the pun!) about the task see [golang context package](https://golang.org/pkg/context/) and [our use of it](https://github.com/habitat-sh/habitat-operator/blob/master/cmd/habitat-operator/main.go#L92-L120)

**Comment by krnowak** [comment]
Other way of reproducing is basically to run the operator inside the cluster, figure out its PID and kill it with SIGTERM as this is what would normally happen to the process when, for example, cluster or operating system is shutting down. But I'd say that running it outside the cluster and terminating it with ctrl-c is tons simpler.
