### ISSUE TITLE
UpdateStrategy incorrectly set to OnDelete for StatefulSets

### ISSUE THREAD

**Issue by indradhanush** [habitat-sh/habitat-operator#235]
The [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates) states that the default for `UpdateStrategy` is `RollingUpdate` if unspecified. However I found this to be set to `OnDelete` at the moment. Applying the following diff fixed the issue:

```
diff --git a/pkg/controller/stateful_sets.go b/pkg/controller/stateful_sets.go
index 3fdebcd..f4d5434 100644
--- a/pkg/controller/stateful_sets.go
+++ b/pkg/controller/stateful_sets.go
@@ -134,6 +134,9 @@ func (hc *HabitatController) newStatefulSet(h *habv1beta1.Habitat) (*appsv1beta1
 					},
 				},
 			},
+			UpdateStrategy: appsv1beta1.StatefulSetUpdateStrategy{
+				Type: appsv1beta1.StatefulSetUpdateStrategyType(appsv1beta1.RollingUpdateDeploymentStrategyType),
+			},
 		},
 	}
```

Also updating from `k8s.io/api/apps/v1beta1` to `k8s.io/api/apps/v1beta2` or `k8s.io/api/apps/v1` should also fix this but it remains to be decided which one to update to.

**Comment by asymmetric** [comment]
Updating to `v1beta2` is the mid-term solution, but it's blocked by https://github.com/habitat-sh/habitat-operator/issues/219#issuecomment-379767016 (the long term one being `v1`).

So for now we should probably go with the patch you posted.

**Comment by indradhanush** [comment]
On applying `examples/config/habitat.yml` on a minikube cluster running kubernetes v1.7.0 gives the following error:
```
ERROR: logging before flag.Parse: E0410 10:59:13.300326       5 reflector.go:205] github.com/habitat-sh/habitat-operator/pkg/controller/controller.go:126: Failed to list *v1beta2.StatefulSet: the server could not find the requested resource
```

We can drop support for 1.7 when we move to 1.10.
