### ISSUE TITLE
Updating yaml for running stateful set gets reverted

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat-operator#248]
When trying to patch or update the yaml for a stateful set that is already deployed, the change gets reverted by the operator. Is there a way to tell the operator that this is an update that it shouldn't revert?

**Comment by krnowak** [comment]
This is unfortunately not how the operator works. If you need to change something in the deployed stateful set that was created by the operator, you need to modify a resource that was a base of the statefulset. In our case - you would need to modify the habitat resource. What could be helpful is to get a warning from the operator when it is about to overwrite your modifications (#252). Also, we are working on the design doc that explains some stuff, see #253.
