### ISSUE TITLE
Move CustomVersion field?

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#262]
From [the docs](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status):

> Objects that contain both spec and status should not contain additional top-level fields other than the standard metadata fields.

We should investigate what the risk of having the `customVersion` field at the top-level is.

Also see #182.

**Comment by asymmetric** [comment]
Asked on the slack channel, [this](https://kubernetes.slack.com/archives/C0EG7JC6T/p1525721170000226) was the response:

> asymmetric [5:44 PM]
> hey everyone, the docs [say](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status) that
> 
>   > Objects that contain both spec and status should not contain additional top-level fields other than the standard metadata fields.
> 
> What's the risk in adding additional top-level fields to a CRD? (edited)

---  
> deads2k [9:26 PM]
> @asymmetric well, there's been at least one bug where the status endpoint incorrectly allowed updates to unknown top-level fields
> @asymmetric also, in kube-like APIs it's an indicator for "user can set" and "user can observe" distinctions
> @asymmetric so you can argue with spec "I want it like this", but you can't argue with status, "the world is the way it is, don't argue with reality"
> we have some types without that distinction (see configmaps and secrets), but they are comparatively rare.  You should ask yourself just how special your type really is

**Comment by asymmetric** [comment]
Our type is not very special, but the `customVersion` field kind of is. It's also temporary, since hopefully at some point CRD versioning will be supported natively.

I think that if we're aware of the possible pitfalls, we can leave things as they are, and simply eliminate `customVersion` when the time comes.

@krnowak?

**Comment by krnowak** [comment]
I would leave as is. It is a workaround for missing CRD functionality, so it does not suit anywhere else. I'd say, let's move it if we encounter a bug that this field causes. Hopefully that won't happen before the support for CRD versioning lands in k8s.

**Comment by asymmetric** [comment]
Agreed. Let's close this then.
