### ISSUE TITLE
Support private repositories (ACR) for the docker container

### ISSUE THREAD

**Issue by jamesc** [habitat-sh/habitat-operator#264]
I'm trying to integrate with ACR which is only a private repository.  It looks like there is no ability to provide an `ImagePullSecrets` into the Pod descriptor.  The canonical example is at https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

**Comment by jamesc** [comment]
For AKS+ACR it looks like we can work around this using the service principal created for AKS - https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks#grant-aks-access-to-acr

So this isn't a showstopper for the AKS usecase but could impact other private docker repository usage

**Comment by jamesc** [comment]
@asymmetric I think that's a much better idea.  Feels like that is just documentation then ? I'll test this on a new cluster in Azure and see if works.

**Comment by asymmetric** [comment]
@jamesc Did you get a chance to test this?

I'm going to close this as I think there's nothing to be done on our side, but let me know if things don't work and we can reopen.

**Comment by indradhanush** [comment]
@irvingpop Hello. I read through the issue and was unable to understand why would we need to reopen it at the moment. :thinking: 
Could you please clarify a bit more?

Nevertheless, it appears that there's an unanswered question from above and I'll do my best:
 
>  Feels like that is just documentation then ?

The approach of using a `ServiceAccount` mentioned in the [above commment](https://github.com/habitat-sh/habitat-operator/issues/264#issuecomment-385957232) already appears to link to a page that documents the process. Besides, it feels that it's better suited to Kubernetes documentation than the operator. I hope it helps. :)

**Comment by irvingpop** [comment]
You're probably right that the `ServiceAccount` route is the "right way", and used by experienced k8s users.

But for newer users, most of the examples out there use `imgPullSecret` on the deployment.  It's not a great experience for users who are learning kubernetes and the habitat-operator together.
