### ISSUE TITLE
Error on starting operator inside AKS

### ISSUE THREAD

**Issue by jamesc** [habitat-sh/habitat-operator#265]
I start the operator inside AKS using the example deployment config `habitat-operator-deployment.yml`. 
 Immediately the log fills with:

```
habitat-operator.default(O): ERROR: logging before flag.Parse: E0501 00:22:03.617248      31 reflector.go:205] github.com/habitat-sh/habitat-operator/pkg/controller/v1beta2/controller.go:131: Failed to list *v1beta1.Habitat: the server could not find the requested resource (get habitats.habitat.sh)
habitat-operator.default(O): ERROR: logging before flag.Parse: E0501 00:22:03.618300      31 reflector.go:205] github.com/habitat-sh/habitat-operator/pkg/controller/v1beta1/controller.go:120: Failed to list *v1beta1.Habitat: the server could not find the requested resource (get habitats.habitat.sh)
```

**Comment by tashimi** [comment]
Looks like the CRD wasn’t created, _or_ didn’t wait long enough for the CRD to be recognized. Suggested work around: try creating the CRD first, then create the deployment that references it

**Comment by jamesc** [comment]
Ok, so it looks like an issue with how the CRD was created.  It had been there for 23h, but on deleting the CRD and the deployment and re-deploying the operator, the problem went away.

**Comment by asymmetric** [comment]
@jamesc can this be closed? Or do you have to apply a workaround to run the operator on AKS?

**Comment by jamesc** [comment]
All works without workaround.  Closing
