### ISSUE TITLE
Run E2E tests on Azure

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#266]
There are many reasons why running E2E tests on minikube on the CI platforms is not ideal

* Test env diverges massively from production
* We are tied to the version of k8s that minikube supports (and usually they don't support patch releases >= 0)
* We have to use "unsupported/undocumented" features (`--vm-driver=none`)
* We cannot test persitent volumes
* Minikube is removing support of `localkube`, and [neither](https://github.com/kubernetes/minikube/issues/2704#issuecomment-385690511) Travis nor Circle will be able to run minikube if they don't update their base images

For all these reasons, we should run our E2E tests on a cloud platform, and Azure is the best candidate for now.

**Comment by krnowak** [comment]
What needs figuring out is if and how we can run e2e tests on azure using latest kubernetes.

**Comment by asymmetric** [comment]
First issue: Azure offers 1.9.6 as the newest version. So in terms of just that, minikube is currently better.

GKE in comparison offers 1.9.7, so only very marginally better.

**Comment by iaguis** [comment]
https://github.com/Azure/AKS/issues/288

**Comment by iaguis** [comment]
It seems there's no RBAC support yet https://github.com/Azure/AKS/issues/250#issuecomment-378114044

**Comment by asymmetric** [comment]
[In theory](https://github.com/Azure/AKS/issues/88), AKS should introduce support for point versions 1-2 weeks after they've been released, but that hasn't happened for 1.10 yet.

I opened an [issue](https://github.com/Azure/AKS/issues/350), let's see.

**Comment by asymmetric** [comment]
@elliott-davis said he'll ask Chef people about switching to another cloud provider. Moving this to blocked for now.

**Comment by asymmetric** [comment]
We're moving to GCE.
