### ISSUE TITLE
Operator Framework

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#268]
CoreOS released the [Operator Framework](https://coreos.com/blog/introducing-operator-framework).

We should explore what the benefits of using it are, and whether it makes sense to base our work on it.

**Comment by iaguis** [comment]
There's also https://github.com/giantswarm/operatorkit :)

**Comment by asymmetric** [comment]
Looked into both, and the OF seems to solve more of our problems.

It has a CLI tool that:
* creates a project with the expected dir layout
* includes/replaces the code generator, so we don't have to use it directly anymore (yes!)

It has the OLM, which should enable dependency management across operators, among other things.

OTOH, operatorkit is more opinionated about the structure of the controller, and it provides much more functinality in its libraries than what `operator-sdk` currently does. But I think this will probably change in the future as `operator-sdk` matures.

**Comment by asymmetric** [comment]
Closing this, for now it seems to me that OF is the best of the two, but it's definitely too early to think of switching.

**Comment by asymmetric** [comment]
Closed again for now, we'll revisit once the project is more mature.
