### ISSUE TITLE
Run tests on all supported k8s versions

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#270]
Since we support 3 versions of Kubernetes, we should also test all of them.

For example, if by accident we introduce a dependency on an API version that isn't supported in previous versions of Kubernetes than the latest one, we won't catch it with our current test suite (which only runs latest).

**Comment by krnowak** [comment]
How about we also start running test on semaphore CI, so we could have 3 CI hooked to the operator repo, so each CI would test one k8s version? :)

**Comment by asymmetric** [comment]
I think this is blocked by our move to running tests on CircleCI.

Once that's done for the current k8s version, we can use [workflows](https://circleci.com/docs/2.0/workflows/) to spawn builds on multiple clusters.

**Comment by kosyfrances** [comment]
Fixed in #304
