### ISSUE TITLE
Use multi-stage Docker images

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#276]
To reduce image size.

See [this](https://docs.docker.com/develop/develop-images/multistage-build/).

**Comment by iaguis** [comment]
Not sure how this benefits us since we don't build inside the docker container.

However, we do build a statically compiled binary so we could do:

```
FROM scratch
```

and avoid having alpine in the image.

**Comment by iaguis** [comment]
https://github.com/habitat-sh/habitat-operator/pull/277

**Comment by asymmetric** [comment]
True! I was over-enthusiastic about this :)
