### ISSUE TITLE
Operator should not force at least three instances in leader topology

### ISSUE THREAD

**Issue by indradhanush** [habitat-sh/habitat-operator#294]
At the moment, if you tried to make a deployment in the `leader` topology and set `count` to 1, you would get the following error:

```
ts=2018-06-01T12:04:42.582493602Z level=error component=controller/v1beta2 msg="Habitat could not be synced, requeueing" err="too few instances: 1, leader-follower topology requires at least 3" obj=redis-habitat/redis
```

The operator should not force this, as the user may have a good reason of starting only one instance initially and then add more progressively. At best, this should be a warning instead of an error.

**Comment by surajssd** [comment]
@indradhanush this was resolved in https://github.com/habitat-sh/habitat-operator/pull/299 ?

**Comment by indradhanush** [comment]
Err, yes. My bad, I should have tagged this in the PR. :sweat_smile:
