### ISSUE TITLE
Rename topology label to habitat-topology

### ISSUE THREAD

**Issue by indradhanush** [habitat-sh/habitat-operator#309]
This:

```TopologyLabel = "topology"```

Should look like:

```HabitatTopologyLabel = "habitat-topology"```

and the usage updated in all places throughout the codebase. This keeps the naming of the labels consistent and creates a convention to prefix "habitat-" to internal labels used by the operator.

**Comment by krnowak** [comment]
Now I think we should namespace it in a bit different way, though. Something like `habitat.sh/habitat-operator/topology`, or `habitat-operator.habitat.sh/topology`, just like k8s is doing with its `statefulset.kubernetes.io/pod-name` label.

**Comment by krnowak** [comment]
`operator.habitat.sh/topology` sounds good.
