### ISSUE TITLE
Clarify installation steps for setting up habitat-operator

### ISSUE THREAD

**Issue by qubitrenegade** [habitat-sh/habitat-operator#322]
Hello,

Installation instructions assume you have installed and correctly configured Go.

However, as someone with little experience I knew nothing about setting GOPATH.

What I had to do, after installing go to get the habitat-operator to work was the following:

```
echo 'export PATH=$PATH:$(go env GOPATH)/bin' >> ~/.profile
```

Then after sourcing `.profile` (or relogging) my `habitat-operator` binary was in my PATH!

Thanks,
- Q

**Comment by krnowak** [comment]
While I don't think that we should document how to set up go, we could add it to the list of prerequisites together with a link to https://golang.org/doc/install.

Same for setting up the kubernetes cluster - we can point the user to minikube (https://kubernetes.io/docs/setup/minikube/)

As for `habitat-operator --kubeconfig ~/.kube/config` command - we can either tell the user to add `$GOPATH/bin` to their `$PATH` or just use `$GOPATH/bin/habitat-operator --kubeconfig ~/.kube/config`.

**Comment by krnowak** [comment]
Other things we could do better in docs is some kind of faq or HowDoI. For example how to configure the service through user.toml, like:

- write the toml file
- encode it in base64
- create a Secret resource (likely together with a link to https://kubernetes.io/docs/concepts/configuration/secret/)
- fill the configSecretName with the name of the secret
- look at this or that example (bind-config for example)
