### ISSUE TITLE
Use ownerReferences with CRD

### ISSUE THREAD

**Issue by LiliC** [habitat-sh/habitat-operator#38]
Using `OwnerReferences` allows us to define relationships between Resources, so that deleting an owner can automatically delete owned resources.

Currently, we use `OwnerReferences` to associate a ConfigMap with a Deployment.

It could be useful to make all Resources we create dependent on the CustomResource, but there might currently be [problems](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#known-issues) with that.

**Comment by asymmetric** [comment]
The issues seem to have been [solved](https://github.com/kubernetes/kubernetes/issues/26120).

**Comment by LiliC** [comment]
@asymmetric Yes, we can use that now in the operator.
