### ISSUE TITLE
Switch to pflag in test

### ISSUE THREAD

**Issue by LiliC** [habitat-sh/habitat-operator#78]
Tried using [pflag](https://github.com/spf13/pflag) but it did not work, because flag registering/parsing seem to get overridden. Maybe it's because other parts of the code/dependencies parse things through init methods, but it needs some further investigation.

My attempt:
```
type testFlag struct {
	image      string
	kubeconfig string
	externalIP string
}
....
flags := flag.NewFlagSet(os.Args[0], flag.ContinueOnError)

flags.StringVar(&tf.image, "image", "", "habitat operator image, 'kinvolk/habitat-operator'")
flags.StringVar(&tf.kubeconfig, "kubeconfig", "", "path to kube config file")
flags.StringVar(&tf.externalIP, "ip", "", "external ip, eg. minikube ip")

flags.Parse(os.Args[2:]) // As the previous flags are test related flags.
```

**Comment by asymmetric** [comment]
See #62.

**Comment by zeenix** [comment]
it this still open or other commits took care of it already?

**Comment by LiliC** [comment]
Yes this is still open, I tried getting it to work in the tests, but had problems with it, and did not want to spend much more time as it's not a huge priority right now.
